import { Psychiatrist, Review, Booking, Complaint, PlatformSettings, PatientAccount } from './types';

export const initialPlatformSettings: PlatformSettings = {
  commissionRate: 18,
  maxBoostedDoctors: 9,
  heroImageUrl: '/hero_bg.jpg',
};

const getFutureSlotISO = (daysAhead: number, hour: number, minute: number = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

export const initialPsychiatrists: Psychiatrist[] = [
  {
    id: 'doc-1',
    name: 'Dr. Ananda Wickramasinghe',
    title: 'Senior Consultant Psychiatrist',
    slmcRegNo: 'SLMC-38491',
    status: 'approved',
    isBoosted: true,
    boostTier: '3-day',
    boostExpiry: getFutureSlotISO(3, 23, 59),
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
    bio: 'Over 16 years of clinical experience in mood disorders, anxiety, and adult cognitive behavioral therapy across Sri Lanka teaching hospitals.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth', 'Audio Call'],
    specialties: ['Depression & Anxiety', 'Bipolar Disorder', 'Stress Management'],
    district: 'Colombo',
    feeLkr: 6000,
    rating: 4.9,
    reviewCount: 42,
    ratingDistribution: { 5: 38, 4: 3, 3: 1, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's101', datetime: getFutureSlotISO(1, 9, 0), durationMins: 45, status: 'available' },
      { id: 's102', datetime: getFutureSlotISO(1, 10, 30), durationMins: 45, status: 'available' },
      { id: 's103', datetime: getFutureSlotISO(2, 14, 0), durationMins: 45, status: 'available' },
      { id: 's104', datetime: getFutureSlotISO(3, 11, 0), durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd1', name: 'SLMC_Board_Certificate_2010.pdf', url: '#', uploadDate: '2024-01-15', status: 'Approved' },
      { id: 'd2', name: 'MBBS_Peradeniya_Degree.pdf', url: '#', uploadDate: '2024-01-15', status: 'Approved' },
    ],
  },
  {
    id: 'doc-2',
    name: 'Dr. Nilakshi Samarasinghe',
    title: 'Child & Adolescent Psychiatrist',
    slmcRegNo: 'SLMC-42109',
    status: 'approved',
    isBoosted: true,
    boostTier: '1-day',
    boostExpiry: getFutureSlotISO(1, 23, 59),
    photo: 'https://images.unsplash.com/photo-1594824813566-78a1ed6a2b4b?q=80&w=600&auto=format&fit=crop',
    bio: 'Dedicated to young minds and neurodevelopmental care. Specialist in ADHD, teen anxiety, and family relational dynamics.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth'],
    specialties: ['Child & Adolescent', 'ADHD Care', 'Family Therapy'],
    district: 'Kandy',
    feeLkr: 5500,
    rating: 4.85,
    reviewCount: 31,
    ratingDistribution: { 5: 27, 4: 3, 3: 1, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's201', datetime: getFutureSlotISO(1, 16, 0), durationMins: 45, status: 'available' },
      { id: 's202', datetime: getFutureSlotISO(2, 15, 0), durationMins: 45, status: 'available' },
      { id: 's203', datetime: getFutureSlotISO(4, 10, 0), durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd3', name: 'SLMC_Reg_Doc_ChildPsych.pdf', url: '#', uploadDate: '2024-03-10', status: 'Approved' },
    ],
  },
  {
    id: 'doc-3',
    name: 'Dr. Kiruba Sathananthan',
    title: 'Consultant Neuropsychiatrist',
    slmcRegNo: 'SLMC-29018',
    status: 'approved',
    isBoosted: true,
    boostTier: '3-day',
    boostExpiry: getFutureSlotISO(3, 23, 59),
    photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=600&auto=format&fit=crop',
    bio: 'Pioneer in trauma-informed care and geriatric psychiatry. Fluent in Tamil, Sinhala, and English with compassionate tele-consultations.',
    languages: ['English', 'Tamil', 'Sinhala'],
    sessionFormats: ['Video Telehealth', 'Audio Call'],
    specialties: ['PTSD & Trauma', 'Geriatric Psychiatry', 'Insomnia & Sleep'],
    district: 'Jaffna',
    feeLkr: 5000,
    rating: 5.0,
    reviewCount: 28,
    ratingDistribution: { 5: 28, 4: 0, 3: 0, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's301', datetime: getFutureSlotISO(1, 11, 0), durationMins: 45, status: 'available' },
      { id: 's302', datetime: getFutureSlotISO(2, 17, 0), durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd4', name: 'Jaffna_General_SLMC.pdf', url: '#', uploadDate: '2023-11-20', status: 'Approved' },
    ],
  },
  {
    id: 'doc-4',
    name: 'Dr. Chaminda Perera',
    title: 'Consultant Addiction Psychiatrist',
    slmcRegNo: 'SLMC-51022',
    status: 'approved',
    isBoosted: false,
    boostTier: 'none',
    boostExpiry: null,
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
    bio: 'Specializing in substance recovery, behavioral addictions, and burnout among working professionals.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth', 'Chat Consultation'],
    specialties: ['Addiction Recovery', 'Workplace Burnout', 'OCD & Panic'],
    district: 'Galle',
    feeLkr: 4800,
    rating: 4.7,
    reviewCount: 19,
    ratingDistribution: { 5: 15, 4: 3, 3: 1, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's401', datetime: getFutureSlotISO(1, 18, 0), durationMins: 45, status: 'available' },
      { id: 's402', datetime: getFutureSlotISO(3, 15, 30), durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd5', name: 'SLMC_Cert_Galle.pdf', url: '#', uploadDate: '2024-05-02', status: 'Approved' },
    ],
  },
  {
    id: 'doc-5',
    name: 'Dr. Thilini Rajapaksha',
    title: 'Consultant Women’s Mental Health Specialist',
    slmcRegNo: 'SLMC-48119',
    status: 'approved',
    isBoosted: false,
    boostTier: 'none',
    boostExpiry: null,
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
    bio: 'Focusing on perinatal mood disorders, postpartum wellness, and hormonal mental health challenges.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth'],
    specialties: ['Perinatal Depression', 'Women’s Health', 'Anxiety & Panic'],
    district: 'Kurunegala',
    feeLkr: 5200,
    rating: 4.92,
    reviewCount: 24,
    ratingDistribution: { 5: 22, 4: 2, 3: 0, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's501', datetime: getFutureSlotISO(1, 18, 0), durationMins: 45, status: 'available' },
      { id: 's502', datetime: getFutureSlotISO(2, 9, 30), durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd6', name: 'SLMC_Perinatal_Creds.pdf', url: '#', uploadDate: '2024-04-18', status: 'Approved' },
    ],
  },
  {
    id: 'doc-6',
    name: 'Dr. Ruwan Gunawardena',
    title: 'Adult Psychiatry Specialist',
    slmcRegNo: 'SLMC-55920',
    status: 'pending',
    isBoosted: false,
    boostTier: 'none',
    boostExpiry: null,
    photo: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?q=80&w=600&auto=format&fit=crop',
    bio: 'Recently submitted credential verification for online consultation on PsyNova platform.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth'],
    specialties: ['General Adult Psychiatry', 'Depression'],
    district: 'Gampaha',
    feeLkr: 4500,
    rating: 0,
    reviewCount: 0,
    ratingDistribution: { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 },
    upcomingSlots: [],
    documents: [
      { id: 'd7', name: 'SLMC_Pending_Verification_2026.pdf', url: '#', uploadDate: '2026-08-01', status: 'Pending' },
    ],
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-101',
    doctorId: 'doc-1',
    doctorName: 'Dr. Ananda Wickramasinghe',
    patientName: 'Dilshan Silva',
    patientDistrict: 'Colombo',
    rating: 5,
    date: '2026-08-16',
    text: 'Exceptional clinical care. Dr. Ananda helped me navigate severe panic disorder and workplace burnout with structured CBT techniques. The video consultation room was crystal clear, secure, and very reassuring.',
    isVerified: true,
    helpfulCount: 14,
    flagged: false,
  },
  {
    id: 'rev-102',
    doctorId: 'doc-2',
    doctorName: 'Dr. Nilakshi Samarasinghe',
    patientName: 'Sanduni Jayawardena',
    patientDistrict: 'Kandy',
    rating: 5,
    date: '2026-08-14',
    text: 'Dr. Nilakshi’s compassionate approach with my 14-year-old daughter’s ADHD and school anxiety made an immense difference. Highly recommend for child and adolescent psychiatry in Sri Lanka.',
    isVerified: true,
    helpfulCount: 9,
    flagged: false,
  },
  {
    id: 'rev-103',
    doctorId: 'doc-3',
    doctorName: 'Dr. Kiruba Sathananthan',
    patientName: 'Priya Ramanathan',
    patientDistrict: 'Jaffna',
    rating: 5,
    date: '2026-08-12',
    text: 'Fluent in Tamil and deeply empathetic. Guided our family through elderly memory care and severe insomnia with utmost dignity and practical coping steps.',
    isVerified: true,
    helpfulCount: 12,
    flagged: false,
  },
  {
    id: 'rev-104',
    doctorId: 'doc-4',
    doctorName: 'Dr. Chaminda Perera',
    patientName: 'Kavinda Fernando',
    patientDistrict: 'Galle',
    rating: 4,
    date: '2026-08-10',
    text: 'Solid clinical guidance on behavioral relapse prevention and stress triggers. The Jitsi tele-room audio and SMS reminders worked smoothly.',
    isVerified: true,
    helpfulCount: 5,
    flagged: false,
  },
  {
    id: 'rev-105',
    doctorId: 'doc-5',
    doctorName: 'Dr. Thilini Rajapaksha',
    patientName: 'Nimna Wickramaratne',
    patientDistrict: 'Kurunegala',
    rating: 5,
    date: '2026-08-08',
    text: 'Outstanding specialist in perinatal mood challenges and postpartum wellness. Provided practical emotional tools without any judgment or stigma.',
    isVerified: true,
    helpfulCount: 8,
    flagged: false,
  },
  {
    id: 'rev-106',
    doctorId: 'doc-1',
    doctorName: 'Dr. Ananda Wickramasinghe',
    patientName: 'Tharindu Perera',
    patientDistrict: 'Gampaha',
    rating: 3,
    date: '2026-08-17',
    text: 'Consultation advice was very helpful, but experienced 5-minute audio lag due to local fiber storm outage before reconnecting.',
    isVerified: true,
    helpfulCount: 2,
    flagged: true,
    adminNote: 'Audited by Admin: Telecom ISP latency confirmed in Gampaha region. Follow-up SMS courtesy credit issued.',
  },
  {
    id: 'rev-107',
    doctorId: 'doc-4',
    doctorName: 'Dr. Chaminda Perera',
    patientName: 'Kavinda Fernando',
    patientDistrict: 'Galle',
    rating: 3,
    date: '2026-08-19',
    text: 'Doctor had to reschedule due to emergency hospital ICU round; session was conducted 1 hour later.',
    isVerified: true,
    helpfulCount: 1,
    flagged: true,
    adminNote: 'Audited by Admin: Doctor verified emergency hospital admission. Rescheduled slot completed with patient consent.',
  },
];

export const initialBookings: Booking[] = [];

export const initialComplaints: Complaint[] = [
  {
    id: 'CMP-1042',
    bookingId: 'BK-84920',
    patientId: 'pat-4',
    patientName: 'Tharindu Perera',
    doctorId: 'doc-1',
    doctorName: 'Dr. Ananda Wickramasinghe',
    reason: 'Telehealth Room Audio Lag & Line Disconnection',
    details: 'During the initial 10 minutes of the session, the room experienced repeated audio buffering due to local fiber maintenance in Gampaha. Requesting 15-minute supplementary follow-up slot.',
    status: 'Pending',
    createdAt: '2026-08-18T15:30:00.000Z',
  },
  {
    id: 'CMP-2819',
    bookingId: 'BK-77312',
    patientId: 'pat-3',
    patientName: 'Kavinda Fernando',
    doctorId: 'doc-4',
    doctorName: 'Dr. Chaminda Perera',
    reason: 'Emergency Reschedule Timing Request',
    details: 'Doctor had an emergency teaching hospital ICU admission; patient requested confirmation of the rescheduled tele-slot for Saturday morning.',
    status: 'Pending',
    createdAt: '2026-08-19T09:15:00.000Z',
  },
  {
    id: 'CMP-3920',
    bookingId: 'BK-65109',
    patientId: 'pat-2',
    patientName: 'Sanduni Jayawardena',
    doctorId: 'doc-2',
    doctorName: 'Dr. Nilakshi Samarasinghe',
    reason: 'Prescription Dosage Clarification Note',
    details: 'Patient requested an updated signed digital prescription note clarifying exact bedtime dosages for child medication.',
    status: 'Resolved',
    createdAt: '2026-08-15T11:20:00.000Z',
    resolutionProof: 'SLMC_Prescription_Clarification_Signed_Ref#42109.pdf',
    resolutionNote: 'Dr. Nilakshi provided signed SLMC dosage clarification memorandum via encrypted patient portal. Resolved and verified.',
  },
  {
    id: 'CMP-4105',
    bookingId: 'BK-52490',
    patientId: 'pat-1',
    patientName: 'Dilshan Silva',
    doctorId: 'doc-3',
    doctorName: 'Dr. Kiruba Sathananthan',
    reason: 'Duplicate PayHere Payment Debit Reversal',
    details: 'Patient bank reported double debit of LKR 5,000 during network gateway timeout. Requested gateway merchant refund.',
    status: 'Resolved',
    createdAt: '2026-08-12T16:45:00.000Z',
    resolutionProof: 'PayHere_Merchant_Reversal_Receipt_#884192.pdf',
    resolutionNote: 'PayHere Merchant Settlement Team completed full LKR 5,000 reversal to patient Commercial Bank account. Reversal confirmed by patient.',
  },
];

export const initialPatients: PatientAccount[] = [];

